"""baseline_decompositions_table

Revision ID: ef18bd8927d7
Revises: 
Create Date: 2026-04-10 21:01:03.718274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef18bd8927d7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decompositions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('request_text', sa.Text(), nullable=False),
    sa.Column('request_type', sa.String(length=64), nullable=False),
    sa.Column('location_id', sa.String(length=128), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=True),
    sa.Column('requester_name', sa.String(length=256), nullable=True),
    sa.Column('request_summary', sa.Text(), nullable=True),
    sa.Column('total_tasks', sa.Integer(), nullable=True),
    sa.Column('total_estimated_days', sa.Integer(), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('decompositions')
    # ### end Alembic commands ###
